
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DATABASE_USERNAME=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DEBUG=${DEBUG}
    expose:
      - "8000"
  
  caddy:
    image: caddy:2.8
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./CaddyFile:/etc/caddy/Caddyfile:ro
      - ./frontend_dist:/srv/frontend:ro
      - caddy_data:/data
      - caddy_config:/config


volumes:
  caddy_data:
  caddy_config: